### ISSUE TITLE
several recommendations

### ISSUE THREAD

**Issue by imp1sh** [brendanbank/gpsd-prometheus-exporter#5]
Hi,

please allow me to recommend / ask for several changes:

1) Installing python requirements via pip is not a good way. Modern distributions do not even allow system-wide pip installations. It's usually better to user the package manager and install e.g. python3-gps / python3-prometheus-client.
2)  The docs contain instructions to clone your repository, yet you give the ssh link, which does not work. Please give the https link.
3) What do I have to do to bind the exporter service on "::" instead of "0.0.0.0". IPv4 is legacy, the default should be an IPv6 enabled scenario.
4) systemd units should be put in /etc/systemd/system rather than /lib/systemd/system. 

Regards
Jochen

**Comment by brendanbank** [comment]
Many thanks Jochen, I've implemented your recommendations. Best - Brendan
